compile_pdf:
  image: aergus/latex
  script:
    - pdflatex main.tex
    - makeglossaries main
    - makeindex main.idx
    - pdflatex main.tex
    - mv main.pdf bind.pdf
  except:
    - dev
    - master
  artifacts:
    paths:
      - bind.pdf
