compile_pdf:
  image: aergus/latex
  script:
    - pdflatex main.tex
    - makeglossaries main
    - makeindex main.idx
    - pdflatex main.tex
  except:
    - dev
  artifacts:
    paths:
      - main.pdf
