compile_pdf:
  image: aergus/latex
  script:
    - pdflatex First_Blood.tex
    - makeglossaries First_Blood
    - makeindex First_Blood.idx
    - pdflatex First_Blood.tex
  except:
    - dev
  artifacts:
    paths:
      - First_Blood.pdf
